echo "## $(date +"%Y-%m-%d %H:%M:%S %z")"

export HISTTIMEFORMAT="%FT%T%z "

for d in $(ls -d /opt/*/ 2> /dev/null); do
    test -d ${d%/}/bin && d=$d/bin
    export PATH=$d:$PATH
done

alias tl='tree -L 1'
alias tl1='tree -L 1'
alias tl2='tree -L 2'
alias tl3='tree -L 3'
alias tl4='tree -L 4'
alias tl5='tree -L 5'
