version: '3'

services:
  hello:
    image: registry.cn-shanghai.aliyuncs.com/d2jvkpn/node-web:latest
    container_name: node-web
    restart: always
    networks: ["hello"]
    ports: ["${PORT}:${PORT}"]
    environment: ["TZ=Asia/Shanghai"]
    command: node server.js --port=${PORT}

networks:
  hello: {name: hello, driver: bridge }
