[[machines]]
name = "machine1"                      # machine name
addr = "root@172.17.0.11:1001"         # ssh username@ip:port
n = 2                                  # number of worker
dir = "/root/wk_julia"                 # work path
exename = "/opt/julia-1.5.3/bin/julia" # julia execute path

[[machines]]
name = "machine2"
addr = "root@172.17.0.12:1001"
n = 2
dir = "/root/wk_julia"
exename = "/opt/julia-1.5.3/bin/julia"


[[machines]]
name = "machine3"
addr = "root@172.17.0.13:1001"
n = 1
dir = "/root/wk_julia"
exename = "/opt/julia-1.5.3/bin/julia"
