- hosts: "{{host}}"
  gather_facts: false
  # any_errors_fatal: true

  vars:
    # work_path: "/root"
    _wd: "{{lookup('env', 'PWD')}}"
    _hd: "{{lookup('env', 'HOME')}}"

  tasks:
  - name: apt update
    become: true
    apt: update_cache=yes force_apt_get=yes cache_valid_time=300

  - name: apt upgrade
    become: true
    apt: upgrade=dist force_apt_get=yes autoremove=true autoclean=true

  - name: clean packages
    become: true
    shell:
      cmd: |
        apt -y clean; apt -y clean; apt -y remove; apt -y autoremove
        dpkg -l | awk '/^rc/{print $2}' | xargs -i dpkg -P {}
